### ISSUE TITLE
Fehlermeldung nach Script Installation auf Pi OS Lite version 11 

### ISSUE THREAD

**Issue by rookie10** [rookie10/doorpi-config#2]
Installation (auf leerer SD mit frischen Pi OS Lite bullseye) war leider nicht erfolgreich. Es gab zwar keine Fehlermeldungen und die neue doorpi-config läuft auch, doch ich kann doorpi nicht starten.

Der Aufruf von doorpi_cli --trace liefert

    rpi@raspberrypi:~ $ sudo /usr/local/bin/doorpi_cli --trace
    Traceback (most recent call last):

    File "/usr/local/bin/doorpi_cli", line 6, in <module>  from pkg_resources import load_entry_point
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>@_call_aside
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_asidef(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set 
    working_set = WorkingSet._build_master()
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master ws.require(__requires__)
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require needed = self.resolve(parse_requirements(requirements))
    File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'requests>=2.7.0' distribution was not found and is required by DoorPi`

**Comment by rookie10** [comment]
Request mit pip unterstützt  ab der Version 2.28.0 python 2.7 nicht mehr. Letzte Version die python 2.7 noch Unterstütz ist die 2.27.1
`sudo python -m pip install requests==2.27.1`

**Comment by rookie10** [comment]
Bei der Installation wird request 2.27.1 fest installiert
