### ISSUE TITLE
DoorPi does not start after the install script

### ISSUE THREAD

**Issue by Kunstflieger** [rookie10/doorpi-config#3]
After install the script with the latest RaspberryOS, DoorPi does not start. 
The logfile says, that python 2.7.0 is missing.

Traceback (most recent call last):
  File "/usr/local/bin/doorpi_cli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests>=2.7.0' distribution was not found and is required by DoorPi

**Comment by Kunstflieger** [comment]
manual install with     sudo python -m pip install requests==2.27.1

**Comment by Kunstflieger** [comment]
I have to reopen the issue since I cannot see in the logfile, why the Webservice did not start.
[doorpi_trace.log](https://github.com/rookie10/doorpi-config/files/9298711/doorpi_trace.log)

**Comment by rookie10** [comment]
Please can you try the current script. The problem is not the webservice, it looks more like an incomplete installation. 
if the problem is still present, please attach the log and the doorpi.confg

**Comment by Kunstflieger** [comment]
After using the new script it works conditionally. No Problem with the default doorpi.ini file.
As soon as I edit the doorpi.ini file somehow the status is still active but the website is offline
[doorpi.txt](https://github.com/rookie10/doorpi-config/files/9382121/doorpi.txt)
[doorpi_default.txt](https://github.com/rookie10/doorpi-config/files/9382122/doorpi_default.txt)
[doorpi_trace.log](https://github.com/rookie10/doorpi-config/files/9382123/doorpi_trace.log)

**Comment by rookie10** [comment]
Your doorpi is still crashing, and the webif can't work

    2022-08-19 14:14:02,559 [ERROR]  	[doorpi.main] Exception NameError: invalid literal for int() with base 10: 'bouncetime'
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.5.1-py2.7.egg/doorpi/main.py", line 152, in main_as_application
    try:                        doorpi.DoorPi(parsed_arguments).run()
    File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.5.1-py2.7.egg/doorpi/doorpi.py", line 232, in run
    if not self.__prepared: self.prepare(self.__parsed_arguments)
    File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.5.1-py2.7.egg/doorpi/doorpi.py", line 147, in prepare
    self.__keyboard     = load_keyboard()
    return KeyboardHandler(config_keyboards)
    File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.5.1-py2.7.egg/doorpi/keyboard/KeyboardInterface.py", line 104, in __init__
    self.__keyboards[keyboard_name] = load_single_keyboard(keyboard_name)
    pressed_on_key_down=pressed_on_key_down
    File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.5.1-py2.7.egg/doorpi/keyboard/from_piface.py", line 13, in get
    def get(**kwargs): return PiFace(**kwargs)
    File "/usr/local/lib/python2.7/dist-packages/DoorPi-2.5.1-py2.7.egg/doorpi/keyboard/from_piface.py", line 24, in __init__
    self._InputPins = map(int, input_pins)
    ValueError: invalid literal for int() with base 10: 'bouncetime'
    2022-08-19 14:14:02,562 [DEBUG]  	[doorpi.doorpi] destroy doorpi`

this is not a installation issue. So it's better you post config issues at the doorpi forum. Here you have a better support
Maybe a solution could  be to delete the bouncetime line here

    [onboardpins_InputPins]
    0 = call:**610#623
    bouncetime = 200

**Comment by rookie10** [comment]
no script issue
